language: node_js
node_js:
  - 10
  - 8
env:
  global:
    - PROJECT_NAME=audit-filter
    - RUST_BACKTRACE=full
    - TRAVIS_RUST_VERSION=nightly
before_script:
  - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=$TRAVIS_RUST_VERSION -y
  - source $HOME/.cargo/env
  - rustup component add clippy-preview
  - rustup target add wasm32-unknown-unknown
  - cargo install wasm-pack
script:
  # if you want the build job to fail when encountering warnings, use
  - cargo clippy -- -D warnings
  - cargo test --verbose
  - wasm-pack build --target nodejs
