[package]
name = "audit-filter"
version = "0.1.0"
authors = ["Greg Guthe <gguthe@mozilla.com>"]
exclude = [
	"tests/fixtures/*",
	"example/*",
]

[dependencies]
serde_json = "1.0.27"
serde = "1.0.79"
serde_derive = "1.0.79"
docopt = "1.0.1"
failure = "0.1.2"
